### ISSUE TITLE
Project does not run.

### ISSUE THREAD

**Issue by jcowin-sigmadzn** [chrissainty/SimpleBlazorTooltip#1]
Steps to Reproduce.
1) Download zip file of code.
2) Extract code.
3) Open solution file in Visual Studio 2022
4) Click run "IIS Express"
5) This error pops up.

OS: Windows 10.

System.Text.Json.JsonException
  HResult=0x80131500
  Message='<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex) in System.Text.Json\ThrowHelper.cs:line 910
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json.Serialization\JsonConverter.cs:line 186
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json\JsonSerializer.cs:line 770
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase) in System.Text.Json\JsonSerializer.cs:line 1127
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options) in System.Text.Json\JsonSerializer.cs:line 1092
   at System.Text.Json.JsonSerializer.ReadAll[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo) in System.Text.Json\JsonSerializer.cs:line 1033
   at System.Text.Json.JsonSerializer.ReadAllUsingOptions[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options) in System.Text.Json\JsonSerializer.cs:line 1120
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream utf8Json, JsonSerializerOptions options) in System.Text.Json\JsonSerializer.cs:line 847
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Components.Web.DevServer.Commands.ServeCommand.Execute() in Microsoft.AspNetCore.Components.Web.DevServer.Commands\ServeCommand.cs:line 23
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in Microsoft.Extensions.CommandLineUtils\CommandLineApplication.cs:line 382
   at Microsoft.AspNetCore.Components.WebAssembly.DevServer.Program.Main(String[] args) in Microsoft.AspNetCore.Components.WebAssembly.DevServer\Program.cs:line 22

  This exception was originally thrown at this call stack:
    System.Text.Json.ThrowHelper.ThrowJsonReaderException(ref System.Text.Json.Utf8JsonReader, System.Text.Json.ExceptionResource, byte, System.ReadOnlySpan<byte>) in ThrowHelper.cs
    System.Text.Json.Utf8JsonReader.ConsumeValue(byte) in Utf8JsonReader.cs
    System.Text.Json.Utf8JsonReader.ReadFirstToken(byte) in Utf8JsonReader.cs
    System.Text.Json.Utf8JsonReader.ReadSingleSegment() in Utf8JsonReader.cs
    System.Text.Json.Utf8JsonReader.Read() in Utf8JsonReader.cs
    System.Text.Json.Serialization.JsonConverter<T>.ReadCore(ref System.Text.Json.Utf8JsonReader, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack) in JsonConverter.cs

Inner Exception 1:
JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.

**Comment by jcowin-sigmadzn** [comment]
Note: If I create a new "Blazor Server Project" and copy over the index and tooltip code. It runs just as expected.
